### ISSUE TITLE
multi guild code overhaull

### ISSUE THREAD

**Issue by Minecrafter8001** [QuietTerminalInteractive/TwitchAnnouncer#5]
Unregister command: does not work, says "You are not registered" when the user Is
Announcement: does not work. Says "processed for 0 guild(s)" when a webhook is sent with a user registered within a guild

**Comment by QuietTerminalInteractive** [comment]
Fixed in [b93debe](https://github.com/QuietTerminalInteractive/TwitchAnnouncer/commit/b93debec2c0762822ea4de8d619cd927ddf311e7)
